Add flutter generative RTL design
intel/rohd-hcl pull request #40
Opened 2023-08-01 03:18 UTC by quekyj

## Description & Motivation

Added generative web UI for generation of the RTL code. 

- BLoC design pattern (cubit)
- Material UI widget

## Related Issue(s)

Nope.

## Testing

- Added unit test for each of the components.
- Added widget test to simulate clicking and assert for correct results.

## Backwards-compatibility

> Is this a breaking change that will not be backwards-compatible? If yes, how so?

No.

## Documentation

> Does the change require any updates to documentation? If so, where? Are they included?

No.

2023-08-01 16:25 UTC, mkorbel1 commented
What's this?
![image](https://github.com/intel/rohd-hcl/assets/75506197/35c5abd3-1a12-44d2-be7a-d2d51ea0df65)

2023-08-01 16:35 UTC, mkorbel1 requested changes
Just started going through, but this is looking really really great!  I'll review the rest soon

2023-08-01 16:35 UTC, mkorbel1 commented on doc/confapp_flutter/README.md
> +- [https://github.com/burhanrashid52/WhatTodo/tree/master/lib](https://github.com/burhanrashid52/WhatTodo/tree/master/lib)
what are these?

2023-08-02 04:19 UTC, Skyquek commented
> What's this?
> ![image](https://github.com/intel/rohd-hcl/assets/75506197/35c5abd3-1a12-44d2-be7a-d2d51ea0df65)
> 

I am not sure why this shows up after build. It doesn't show this when I run flutter run -d chrome. I suspect it is a flutter bug.

2023-08-07 03:22 UTC, quekyj commented
> > What's this?
> > ![image](https://user-images.githubusercontent.com/75506197/257580245-35c5abd3-1a12-44d2-be7a-d2d51ea0df65.png)
> 
> I am not sure why this shows up after build. It doesn't show this when I run flutter run -d chrome. I suspect it is a flutter bug.

Fixed this.

2023-09-06 16:19 UTC, mkorbel1 requested changes
Great start!  A little clean-up to do, doesn't have to be perfect for first merge

2023-09-06 16:19 UTC, mkorbel1 commented on confapp_flutter/README.md
Minor, but naming the folder "confapp_flutter" seems a little off.  Maybe "config_app" or just "confapp" would be better, since the flutter part is really just an implementation

2023-09-06 16:19 UTC, mkorbel1 commented on confapp_flutter/lib/hcl/models/component.dart
> +    notifyListeners();
what's this?

2023-09-06 16:19 UTC, mkorbel1 commented on confapp_flutter/lib/hcl/view/hcl_page.dart
> +  /// {@macro counter_page}
left-over comment?

2023-09-06 16:19 UTC, mkorbel1 commented on confapp_flutter/lib/hcl/view/hcl_view.dart
> +  List<Widget> textFormField = []; // shared variable
I'm confused what this list is doing?

2023-09-06 16:19 UTC, mkorbel1 commented on lib/src/memory.dart
why is this here?  i think in main it moved to a different directory

2023-09-06 16:19 UTC, mkorbel1 commented on pubspec.yaml
> +publish_to: none
This shouldn't be necessary?  We are going to be publishing it eventually (soon?)

2023-09-06 16:19 UTC, mkorbel1 commented on test/rf_test.dart
I think this got replaced with memory_test.dart, shouldn't be in here

2023-09-10 05:26 UTC, quekyj commented
Close this pull request. The development of the flutter UI will be move to https://github.com/mkorbel1/rohd-hcl/tree/flutter_refactor instead.

2023-09-10 05:26 UTC, closed without merging