rohd-hcl: parity
intel/rohd-hcl pull request #47
Opened 2023-09-28 14:14 UTC by RPG-coder-intc

## Description & Motivation

Note: Requires Find PR #37  to be merged in before this PR.

A modules for adding functionality of Parity.

Contains 2 modules for parity functionality:
1. ParityTransmitter Module - Appends parity bits to given data that can be used for transmission
2. ParityReceiver Module - 
    - Takes the transmitted data with parity bit. 
    - Splits the data into original data and parity bit. 
    - Also checks for parity error (result) within original data

## Related Issue(s)

Related to issue #39 

## Testing

Testing is handled within `/test/parity_test.dart`

## Backwards-compatibility

Yes, this PR is backward compatible. This is an added functionality. 
Prior modules are not unaffected or reused for completion of this functionality.

## Documentation

Documentation is handled.

2023-09-28 14:17 UTC, RPG-coder-intc commented
@mkorbel1 this PR is ready for a review. also note: this PR contains files from #37

2023-09-28 18:20 UTC, mkorbel1 requested changes
Looks good!  Just some minor tweaks

2023-10-05 18:09 UTC, RPG-coder-intc commented on lib/src/parity.dart
> +    final transmitData = [bus, bus.xor()].swizzle();
done

2023-10-05 18:09 UTC, RPG-coder-intc commented on doc/parity.md
> +ROHD HCL implements `Parity` functionality class that other modules can extend for error checking. For satisfying the functionality of Parity error checking in `Logic` data, ROHD HCL provides 2 `Modu
done

2023-10-05 18:15 UTC, RPG-coder-intc commented on lib/src/parity.dart
> +  /// Construct a module
done

2023-10-12 17:53 UTC, mkorbel1 approved these changes
Looks good to me, nice work!  Once he find/count stuff merges in, we can merge this.

Be sure to merge in that branch's new fixes into this branch to avoid any merge conflicts.

2023-10-12 20:23 UTC, mkorbel1 approved these changes

2023-10-12 20:24 UTC, mkorbel1 approved these changes

2023-10-23 16:33 UTC, RPG-coder-intc commented
@mkorbel1 @chaparalas @quekyj  can this pr be merged in :)

2023-10-23 17:02 UTC, mkorbel1 commented
Sorry for the delay!

2023-10-23 17:02 UTC, merged

2023-10-23 17:05 UTC, RPG-coder-intc commented
> Sorry for the delay!

No worries :) Thanks...